import { Component, inject, OnInit, signal } from '@angular/core';
import { forkJoin } from 'rxjs';
import { SwitchLabEcommerceComponent as EcommerceModuleStatus, SwitchLabEcommerceScenario } from '../../core/models/product-contracts.models';
import { SwitchLabEcommerceService } from '../../core/services/switchlab-ecommerce.service';
@Component({selector:'app-switchlab-ecommerce',standalone:true,template:`
<div class="page-header"><p class="eyebrow">SwitchLab · Lot 6</p><h1><i class="pi pi-shopping-cart"></i> E-commerce & 3DS</h1><p>Chaîne site marchand, gateway Visa/Mastercard et réseau 3DS simulé.</p></div>
@if(error()){<div class="notice error">{{error()}}</div>}
<section class="flow">@for(item of components();track item.code){<article class="card"><header><strong>{{item.label}}</strong><span [class.up]="item.status==='UP'">{{item.status}}</span></header><code>{{item.moduleCode}}</code><div class="tags">@for(capability of item.capabilities;track capability){<span>{{capability}}</span>}</div>@for(limit of item.limitations;track limit){<small>{{limit}}</small>}</article>}</section>
<section class="list"><h2>Scénarios 3DS et paiement</h2><div class="notice"><i class="pi pi-shield"></i>Le frontend n’accepte ni PAN, ni expiration, ni OTP. Les actions restent bloquées jusqu’au résolveur serveur.</div>@for(item of scenarios();track item.code){<article class="card scenario"><div><strong>{{item.label}}</strong><p>{{item.program}} · {{item.flow}}</p><code>{{item.code}}</code><small>{{item.limitation}}</small></div><button type="button" [disabled]="!item.executable">Exécuter</button></article>}</section>
`,styles:[`.page-header h1{display:flex;gap:10px;align-items:center;margin:0}.page-header i{color:var(--sg-color-primary)}.page-header p,.card p,small{color:var(--sg-text-muted)}.eyebrow{text-transform:uppercase;font-size:11px;letter-spacing:.08em}.flow{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:12px}.card,.notice{padding:16px;margin-top:12px;border:1px solid var(--sg-border);border-radius:var(--sg-radius);background:var(--sg-bg-surface)}.card header,.scenario{display:flex;justify-content:space-between;gap:12px}.tags{display:flex;flex-wrap:wrap;gap:5px;margin:12px 0}.tags span{padding:4px 7px;border-radius:999px;background:var(--sg-bg-muted);font-size:11px}.card small{display:block;margin-top:6px}.up{color:#16803c}.scenario{align-items:center}.scenario button{padding:9px}.error{color:#b42318}code{overflow-wrap:anywhere}`]})
export class SwitchLabEcommerceComponent implements OnInit{private readonly service=inject(SwitchLabEcommerceService);readonly components=signal<EcommerceModuleStatus[]>([]);readonly scenarios=signal<SwitchLabEcommerceScenario[]>([]);readonly error=signal<string|null>(null);ngOnInit():void{forkJoin({components:this.service.components(),scenarios:this.service.scenarios()}).subscribe({next:data=>{this.components.set(data.components);this.scenarios.set(data.scenarios)},error:()=>this.error.set('Le cockpit E-commerce & 3DS est indisponible.')})}}
