package com.staging.sg.way4aura.domain;

public enum AuraBindingType {
    SENDER, INSTITUTION, ORDER_DEPARTMENT,
    CLIENT_TYPE, CLIENT_CATEGORY,
    ACCOUNT_PRODUCT, ACCOUNT_SCHEME, SERVICE_PACK,
    PAYMENT_ADDRESS_TYPE, POS_PRODUCT, DEVICE_TYPE,
    COUNTRY, CURRENCY, MCC, WORKFLOW
}
