package com.staging.sg.way4aura.domain;

public enum AuraBindingType {
    SENDER, INSTITUTION, ORDER_DEPARTMENT,
    CLIENT_TYPE, CLIENT_CATEGORY,
    GROUP_PRODUCT, CHAIN_PRODUCT, ACCOUNT_PRODUCT, ACCOUNT_SCHEME, SERVICE_PACK,
    PAYMENT_ADDRESS_TYPE, POS_PRODUCT, DEVICE_ACCOUNT_SCHEME, DEVICE_SERVICE_PACK, DEVICE_TYPE,
    COUNTRY, CURRENCY, MCC, WORKFLOW
}
