package com.staging.sg.way4aura.domain;
public enum Way4ApplicationStatus { PENDING, GENERATED, SUBMITTED, ACCEPTED, RECONCILED,
    MAPPING_BLOCKED, WAY4_REJECTED_RETRYABLE, WAY4_REJECTED_FINAL, RECONCILIATION_REQUIRED }
