package com.staging.sg.way4aura.domain;
public enum Way4FileStatus { DRAFT, VALIDATED, STAGED, SUBMITTED, ACKNOWLEDGED, COMPLETED,
    XSD_REJECTED, STAGE_FAILED, SUBMISSION_FAILED, PARTIALLY_COMPLETED, FAILED_FINAL }
