import { Component, inject, OnInit, signal } from '@angular/core';
import { SwitchLabIndustrialReadiness } from '../../core/models/product-contracts.models';
import { SwitchLabIndustrializationService } from '../../core/services/switchlab-industrialization.service';
@Component({selector:'app-switchlab-industrialization',standalone:true,template:`
<div class="page-header"><p class="eyebrow">SwitchLab · Lot 7</p><h1><i class="pi pi-shield"></i> Industrialisation</h1><p>Readiness commerciale, sauvegarde, audit, licences, sécurité et observabilité.</p><button type="button" (click)="backup()"><i class="pi pi-download"></i> Sauvegarder la configuration</button></div>
@if(error()){<div class="notice error">{{error()}}</div>}
<div class="notice"><i class="pi pi-info-circle"></i>La sauvegarde ne contient aucun secret. La restauration reste bloquée jusqu’au workflow Maker/Checker.</div>
<section class="grid">@for(item of items();track item.code){<article class="card"><header><strong>{{item.label}}</strong><span [class.ready]="item.status==='READY'">{{item.status}}</span></header><code>{{item.code}}</code>@if(item.evidence){<p>{{item.evidence}}</p>}@if(item.limitation){<p class="limit">{{item.limitation}}</p>}</article>}</section>
`,styles:[`.page-header{position:relative}.page-header h1{display:flex;gap:10px;align-items:center;margin:0}.page-header h1 i{color:var(--sg-color-primary)}.page-header p,.card p{color:var(--sg-text-muted)}.page-header button{padding:9px;border:1px solid var(--sg-border-strong);border-radius:var(--sg-radius)}.eyebrow{text-transform:uppercase;font-size:11px;letter-spacing:.08em}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:12px}.card,.notice{padding:16px;margin-top:12px;border:1px solid var(--sg-border);border-radius:var(--sg-radius);background:var(--sg-bg-surface)}.card header{display:flex;justify-content:space-between;gap:12px}.ready{color:#16803c}.limit{color:#9a6700!important}.error{color:#b42318}code{display:block;margin-top:9px}`]})
export class SwitchLabIndustrializationComponent implements OnInit{private readonly service=inject(SwitchLabIndustrializationService);readonly items=signal<SwitchLabIndustrialReadiness[]>([]);readonly error=signal<string|null>(null);ngOnInit():void{this.service.readiness().subscribe({next:value=>this.items.set(value),error:()=>this.error.set('La readiness industrielle est indisponible.')})}backup():void{this.service.backup().subscribe({next:blob=>{const href=URL.createObjectURL(blob);const link=document.createElement('a');link.href=href;link.download='switchlab-configuration-backup.json';link.click();URL.revokeObjectURL(href)},error:()=>this.error.set('La sauvegarde de configuration a échoué.')})}}
