package com.staging.sg.fraud.domain;
import jakarta.persistence.*;import java.time.Instant;import java.util.UUID;
@Entity @Table(name="fraud_event_outbox",uniqueConstraints=@UniqueConstraint(name="uk_fraud_outbox_business_event",columnNames={"member_id","aggregate_type","aggregate_id","event_type"}))
public class FraudEventOutbox{
 @Id private UUID id;@Column(name="member_id",nullable=false,length=64,updatable=false)private String memberId;@Column(name="sector_id",nullable=false,length=64,updatable=false)private String sectorId;@Column(name="aggregate_type",nullable=false,length=48,updatable=false)private String aggregateType;@Column(name="aggregate_id",nullable=false,length=128,updatable=false)private String aggregateId;@Column(name="event_type",nullable=false,length=64,updatable=false)private String eventType;@Column(name="payload_json",nullable=false,length=8000,updatable=false)private String payloadJson;@Column(nullable=false,length=24)private String status;@Column(name="attempt_count",nullable=false)private int attemptCount;@Column(name="next_attempt_at",nullable=false)private Instant nextAttemptAt;@Column(name="created_at",nullable=false,updatable=false)private Instant createdAt;@Column(name="published_at")private Instant publishedAt;protected FraudEventOutbox(){}
 public static FraudEventOutbox pending(String memberId,String sectorId,String aggregateType,String aggregateId,String eventType,String payload){FraudEventOutbox v=new FraudEventOutbox();v.id=UUID.randomUUID();v.memberId=memberId;v.sectorId=sectorId;v.aggregateType=aggregateType;v.aggregateId=aggregateId;v.eventType=eventType;v.payloadJson=payload;v.status="PENDING";v.nextAttemptAt=Instant.now();v.createdAt=v.nextAttemptAt;return v;}
 public UUID id(){return id;}public String memberId(){return memberId;}public String sectorId(){return sectorId;}public String aggregateId(){return aggregateId;}public String status(){return status;}public String eventType(){return eventType;}public String payloadJson(){return payloadJson;}public int attemptCount(){return attemptCount;}public Instant nextAttemptAt(){return nextAttemptAt;}
 public void published(){status="PUBLISHED";publishedAt=Instant.now();}
 public void retry(Instant now,int maxAttempts){attemptCount++;if(attemptCount>=maxAttempts){status="DEAD_LETTER";nextAttemptAt=now;}else{status="PENDING";long seconds=Math.min(300L,1L<<Math.min(attemptCount,8));nextAttemptAt=now.plusSeconds(seconds);}}
}
