server:
  port: ${WAY_POS_SIMULATOR_REST_PORT:8532}

spring:
  application:
    name: wayPosSimulator

way-pos-simulator:
  host: ${WAY_POS_SERVER_HOST:localhost}
  port: ${WAY_POS_SERVER_ISO_PORT:8531}
  timeout-seconds: ${WAY_POS_SIMULATOR_TIMEOUT_SECONDS:55}
  terminal-id: ${WAY_POS_TERMINAL_ID:TERM0001}
  merchant-id: ${WAY_POS_MERCHANT_ID:MERCHANT0000001}
  currency: ${WAY_POS_CURRENCY:504}
  mac-mode: ${WAY_POS_MAC_MODE:BIN}
  tak-hex: ${WAY_POS_TAK_HEX:}
  master-key-id: ${WAY_POS_MASTER_KEY_ID:00}
  master-key-type: ${WAY_POS_MASTER_KEY_TYPE:TMK}
  master-key-hex: ${WAY_POS_MASTER_KEY_HEX:}
  ansi-x917-block-encoding: ${WAY_POS_X917_BLOCK_ENCODING:BINARY}
  ansi-x917-cipher-mode: ${WAY_POS_X917_CIPHER_MODE:ECB}
