import { Component, inject, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { forkJoin } from 'rxjs';
import { SwitchInterfaceCapability, SwitchInterfaceDefinition, SwitchInterfaceRequest } from '../../core/models/product-contracts.models';
import { SwitchInterfaceService } from '../../core/services/switch-interface.service';

@Component({selector:'app-switch-interfaces',standalone:true,imports:[FormsModule],template:`
<div class="page-header"><p class="eyebrow">FuturPayment Switch · Lot 1</p><h1><i class="pi pi-link"></i> Registre d’interfaces</h1><p>Interfaces membre, routage, failover et références cryptographiques.</p></div>
@if(error()){<div class="notice error">{{error()}}</div>}
@if(capability();as cap){<div class="notice" [class.ready]="cap.registryAvailable"><strong>{{cap.registryAvailable?'REGISTRE DISPONIBLE':'REGISTRE BLOQUÉ'}}</strong><span>{{cap.reason}}</span><span>Maker/Checker {{cap.makerCheckerAvailable?'disponible':'indisponible'}}</span></div>}
<form class="card form"><h2>Déclarer une interface</h2><label>Code<input name="code" [(ngModel)]="form.code" /></label><label>Nom<input name="name" [(ngModel)]="form.name" /></label><label>Banque<input name="bank" [(ngModel)]="form.bankCode" /></label><label>Réseau<select name="network" [(ngModel)]="form.network"><option>MASTERCARD</option><option>VISA</option><option>SWAM</option><option>INTERNAL</option></select></label><label>Protocole<input name="protocol" [(ngModel)]="form.protocol" /></label><label>Format<input name="format" [(ngModel)]="form.messageFormat" /></label><label>Hôte<input name="host" [(ngModel)]="form.host" /></label><label>Port<input name="port" type="number" [(ngModel)]="form.port" /></label><label>Priorité<input name="priority" type="number" [(ngModel)]="form.priority" /></label><label>Interface de secours<input name="failover" [(ngModel)]="form.failoverInterfaceCode" /></label><label>Référence certificat<input name="certificate" [(ngModel)]="form.certificateReference" placeholder="vault://certificates/..." /></label><label>Référence clé<input name="key" [(ngModel)]="form.keyReference" placeholder="hsm://keys/..." /></label><button type="button" [disabled]="!canCreate()">Soumettre au Maker/Checker</button></form>
<section class="list"><h2>Interfaces déclarées</h2>@for(item of interfaces();track item.id){<article class="card"><header><div><strong>{{item.name}}</strong><code>{{item.code}}</code></div><span>{{item.status}} · {{item.connectionStatus}}</span></header><p>{{item.network}} · {{item.protocol}}/{{item.messageFormat}} · {{item.host}}:{{item.port}}</p><p>Priorité {{item.priority}} · secours {{item.failoverInterfaceCode||'—'}}</p><p><code>{{item.certificateReference||'Aucun certificat'}}</code> · <code>{{item.keyReference||'Aucune clé'}}</code></p><div class="actions">@for(action of item.allowedActions;track action){<button type="button" disabled>{{action}}</button>}</div></article>}@empty{<div class="notice">Aucune interface réelle retournée par le backend membre.</div>}</section>
`,styles:[`.page-header h1{display:flex;gap:10px;align-items:center;margin:0}.page-header i{color:var(--sg-color-primary)}.page-header p,.card p{color:var(--sg-text-muted)}.eyebrow{text-transform:uppercase;font-size:11px;letter-spacing:.08em}.card,.notice{padding:16px;margin-top:12px;border:1px solid var(--sg-border);border-radius:var(--sg-radius);background:var(--sg-bg-surface)}.notice{display:flex;gap:14px;flex-wrap:wrap}.ready{color:#16803c}.error{color:#b42318}.form{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.form h2{grid-column:1/-1;margin:0}.form label{display:flex;flex-direction:column;gap:5px}.form input,.form select,.form button,.actions button{padding:9px;border:1px solid var(--sg-border-strong);border-radius:var(--sg-radius)}.card header{display:flex;justify-content:space-between;gap:12px}.card header code{display:block}.actions{display:flex;gap:7px}@media(max-width:900px){.form{grid-template-columns:1fr}.form h2{grid-column:auto}}`]
})
export class SwitchInterfacesComponent implements OnInit{private readonly service=inject(SwitchInterfaceService);readonly capability=signal<SwitchInterfaceCapability|null>(null);readonly interfaces=signal<SwitchInterfaceDefinition[]>([]);readonly error=signal<string|null>(null);form:SwitchInterfaceRequest={code:'',name:'',bankCode:'',network:'MASTERCARD',protocol:'TCP',messageFormat:'ISO8583',host:'',port:0,priority:1,failoverInterfaceCode:'',certificateReference:'vault://',keyReference:'hsm://'};ngOnInit():void{forkJoin({capability:this.service.capability(),interfaces:this.service.interfaces()}).subscribe({next:data=>{this.capability.set(data.capability);this.interfaces.set(data.interfaces)},error:()=>this.error.set('Le backend Switch membre ou la session Switch est indisponible.')})}canCreate():boolean{const cap=this.capability();return !!cap?.registryAvailable&&!!cap.makerCheckerAvailable}}
