package com.staging.sg.waypos.server.service;

import com.staging.sg.waypos.server.domain.PosTerminalProfile;
import com.staging.sg.waypos.server.repository.PosTerminalProfileRepository;
import org.jpos.iso.ISOMsg;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;

@Service
public class WayPosSystemMessageService {
    private final PosTerminalProfileRepository terminals;
    private final WayPosKeyExchangeService keyExchange;
    private final WayPosReconciliationService reconciliation;
    private final WayPosFileUpdateService fileUpdates;

    public WayPosSystemMessageService(
            PosTerminalProfileRepository terminals,
            WayPosKeyExchangeService keyExchange,
            WayPosReconciliationService reconciliation,
            WayPosFileUpdateService fileUpdates) {
        this.terminals = terminals;
        this.keyExchange = keyExchange;
        this.reconciliation = reconciliation;
        this.fileUpdates = fileUpdates;
    }

    public boolean supports(ISOMsg message) {
        try {
            String mti = message.getMTI();
            return mti.startsWith("03") || mti.startsWith("05")
                    || mti.startsWith("08");
        } catch (Exception e) {
            return false;
        }
    }

    @Transactional
    public ISOMsg process(ISOMsg request) throws Exception {
        String terminalId = request.hasField(41) ? request.getString(41) : null;
        PosTerminalProfile terminal = terminalId == null ? null
                : terminals.findLockedByTerminalId(terminalId).orElse(null);
        if (terminal == null || !terminal.isEnabled()) {
            return response(request, "03", null);
        }
        String mti = request.getMTI();
        String processingCode = request.hasField(3) ? request.getString(3) : "";
        if ("0302".equals(mti)) {
            boolean accepted = fileUpdates.receive(request, terminalId);
            return response(request, accepted ? "00" : "30", null);
        }
        if (mti.startsWith("03")) {
            if (!"BATCH_UPLOAD_REQUIRED".equals(terminal.getBatchStatus())) {
                return response(request, "95", terminal.getBatchId());
            }
            boolean accepted = reconciliation.recordBatchUpload(
                    request, terminalId, terminal.getBatchId());
            return response(
                    request, accepted ? "00" : "30", terminal.getBatchId());
        }
        if (mti.startsWith("08") && "930000".equals(processingCode)) {
            keyExchange.confirm(request, terminal);
            return response(request, "00", terminal.getBatchId());
        }
        if (mti.startsWith("08") && "960000".equals(processingCode)) {
            // X9.17 blocks are provisioned/generated by the HSM boundary.
            if (terminal.getTakUnderLmk() == null) {
                return response(request, "96", null);
            }
            var keyFields = keyExchange.exchange(request, terminal);
            ISOMsg response = response(request, "00", null);
            response.unset(63);
            if (!keyFields.isEmpty()) response.set(48, keyFields.get(0));
            if (keyFields.size() > 1) response.set(59, keyFields.get(1));
            return response;
        }
        if (mti.startsWith("05") && "920000".equals(processingCode)) {
            String requestBatch = request.hasField(60) ? request.getString(60) : null;
            if (requestBatch == null || !requestBatch.equals(terminal.getBatchId())) {
                return response(request, "01", terminal.getBatchId());
            }
            boolean advice = mti.startsWith("052");
            boolean useUploads = advice
                    && "BATCH_UPLOAD_REQUIRED".equals(terminal.getBatchStatus());
            boolean matches = reconciliation.matches(
                    terminalId, terminal.getBatchId(), request.getString(63), useUploads);
            String closedBatch = terminal.getBatchId();
            if (!matches) {
                if (advice) terminal.requireManualReconciliation();
                else terminal.requireBatchUpload();
                terminals.save(terminal);
                return response(request, "95", closedBatch);
            }
            if (advice && !useUploads) {
                return response(request, "95", closedBatch);
            }
            terminal.nextBatch();
            terminals.save(terminal);
            return response(request, "00", closedBatch);
        }
        return response(request, "12", null);
    }

    private ISOMsg response(ISOMsg request, String rc, String batchId) throws Exception {
        ISOMsg response = new ISOMsg();
        response.setPackager(request.getPackager());
        char[] mti = request.getMTI().toCharArray();
        if (mti[2] != '0' && mti[2] != '2') {
            throw new IllegalArgumentException("Unsupported request MTI " + request.getMTI());
        }
        mti[2] = (char) (mti[2] + 1);
        response.setMTI(new String(mti));
        copy(request, response, 2, 3, 4, 7, 11, 24, 37, 41, 42, 49, 63);
        ZonedDateTime now = ZonedDateTime.now();
        response.set(12, now.format(DateTimeFormatter.ofPattern("HHmmss")));
        response.set(13, now.format(DateTimeFormatter.ofPattern("MMdd")));
        response.set(39, rc);
        if (batchId != null) response.set(60, batchId);
        return response;
    }

    private static void copy(ISOMsg from, ISOMsg to, int... fields) throws Exception {
        for (int field : fields) {
            if (from.hasField(field)) to.set(field, from.getString(field));
        }
    }
}
