package com.staging.sg.fraud.gateway.service;

import com.fasterxml.jackson.databind.JsonNode;import com.staging.sg.fraud.gateway.api.IsoFraudApi.IsoMessageRequest;import com.staging.sg.fraud.gateway.crypto.FraudKeyExchangeHsm;import org.jpos.iso.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.stereotype.Component;import java.util.*;
@Component public class PermanentIsoMessageProcessor{
 private final Iso8583FraudMapper mapper;private final FraudPlatformClient platform;private final FraudKeyExchangeHsm hsm;private final String signOn,echo,keyRequest,keyDelivery,keyAck,memberId,zmkReference;private final int envelopeField,kcvField,scoreField;
 @Value("${fraud-gateway.iso.rc-allow:00}")private String allowRc="00";@Value("${fraud-gateway.iso.rc-alert:00}")private String alertRc="00";@Value("${fraud-gateway.iso.rc-challenge:00}")private String challengeRc="00";@Value("${fraud-gateway.iso.rc-hold:00}")private String holdRc="00";@Value("${fraud-gateway.iso.rc-block:00}")private String blockRc="00";
 public PermanentIsoMessageProcessor(Iso8583FraudMapper mapper,FraudPlatformClient platform,FraudKeyExchangeHsm hsm,
  @Value("${fraud-gateway.iso.sign-on-code:001}")String signOn,@Value("${fraud-gateway.iso.echo-code:301}")String echo,@Value("${fraud-gateway.iso.key-request-code:101}")String keyRequest,@Value("${fraud-gateway.iso.key-delivery-code:161}")String keyDelivery,@Value("${fraud-gateway.iso.key-ack-code:162}")String keyAck,@Value("${fraud-gateway.iso.member-id:}")String memberId,@Value("${fraud-gateway.iso.zmk-reference:}")String zmkReference,@Value("${fraud-gateway.iso.key-envelope-field:96}")int envelopeField,@Value("${fraud-gateway.iso.key-kcv-field:48}")int kcvField,@Value("${fraud-gateway.iso.score-response-field:63}")int scoreField){this.mapper=mapper;this.platform=platform;this.hsm=hsm;this.signOn=signOn;this.echo=echo;this.keyRequest=keyRequest;this.keyDelivery=keyDelivery;this.keyAck=keyAck;this.memberId=memberId;this.zmkReference=zmkReference;this.envelopeField=envelopeField;this.kcvField=kcvField;this.scoreField=scoreField;}
 public ISOMsg process(ISOMsg request)throws Exception{
  if("0800".equals(request.getMTI()))return network(request);
  if(Set.of("0200","0220","0320").contains(request.getMTI()))return score(request);
  return response(request,"30");
 }
 private ISOMsg network(ISOMsg request)throws Exception{String function=request.hasField(70)?request.getString(70):"";if(signOn.equals(function)||echo.equals(function)||keyAck.equals(function))return response(request,"00");if(keyRequest.equals(function)){requireKeyConfiguration();var envelope=hsm.generateTakUnderZmk(memberId,zmkReference);ISOMsg out=response(request,"00");out.set(70,keyDelivery);if(envelopeField==96)out.set(envelopeField,ISOUtil.hex2byte(envelope.encryptedTak()));else out.set(envelopeField,envelope.encryptedTak());out.set(kcvField,envelope.kcv());return out;}return response(request,"30");}
 private ISOMsg score(ISOMsg request)throws Exception{if(request.hasField(2))return response(request,"30");Map<String,String> fields=new LinkedHashMap<>();for(int f:new int[]{3,4,18,19,22,37,41,42,48,49,62})if(request.hasField(f))fields.put(String.valueOf(f),request.getString(f));JsonNode scored=platform.scorePermanentLink(mapper.toCanonical(new IsoMessageRequest(request.getMTI(),fields)));String enforced=scored.path("enforcedAction").asText("ALERT");ISOMsg out=response(request,responseCode(enforced));out.set(scoreField,"FRAUD_SCORE="+scored.path("score").asInt()+";RECOMMENDED="+scored.path("recommendedAction").asText()+";ENFORCED="+enforced);return out;}
 private ISOMsg response(ISOMsg request,String rc)throws Exception{ISOMsg out=new ISOMsg();out.setPackager(request.getPackager());out.setMTI(responseMti(request.getMTI()));for(int f:new int[]{3,4,7,11,18,19,22,24,32,33,37,41,42,49,70})if(request.hasField(f))out.set(f,request.getString(f));out.set(39,rc);return out;}
 private String responseMti(String mti){char[] value=mti.toCharArray();value[2]=(char)(value[2]+1);return new String(value);}
 private void requireKeyConfiguration(){if(memberId.isBlank()||zmkReference.isBlank())throw new IllegalStateException("Member and HSM ZMK reference are required for TAK exchange");}
 private String responseCode(String action){return switch(action){case"ALLOW"->allowRc;case"CHALLENGE"->challengeRc;case"HOLD"->holdRc;case"BLOCK"->blockRc;default->alertRc;};}
}
