import { DatePipe } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { forkJoin, finalize } from 'rxjs';
import { SoftPosDeviceStatus, SoftPosRoute } from '../../core/models/softpos.models';
import { SoftPosAdminService } from '../../core/services/softpos-admin.service';

@Component({
  selector:'app-softpos-workspace', standalone:true, imports:[DatePipe,FormsModule],
  template:`
  <header class="page-header"><div><p class="eyebrow">Switch · acceptation mobile</p><h1><i class="pi pi-mobile"></i> SoftPOS</h1><p>Terminaux, appareils, routes POServer et transactions du membre connecté.</p></div><button (click)="load()" [disabled]="busy()"><i class="pi pi-refresh"></i> Actualiser</button></header>
  @if(error()){<section class="notice error">{{error()}}</section>}
  <section class="summary"><article><span>Appareils</span><strong>{{devices().length}}</strong></article><article><span>Actifs</span><strong>{{activeDevices()}}</strong></article><article><span>Routes actives</span><strong>{{activeRoutes()}}</strong></article><article><span>Transactions</span><strong>{{transactions().length}}</strong></article></section>
  <section class="panel"><div class="panel-title"><div><h2>Appareils SoftPOS</h2><p>L’identité bancaire provient de la session ; aucun membre ne peut être saisi ici.</p></div><button (click)="issueActivation()">Nouvelle activation</button></div>
    <div class="table"><div class="row head"><span>Terminal</span><span>Commerçant / PDV</span><span>Version</span><span>État</span><span>Action</span></div>
    @for(d of devices();track d.deviceId){<div class="row"><code>{{d.terminalId}}</code><span>{{d.merchantId}}<small>{{d.outletId}}</small></span><span>{{d.applicationVersion}}</span><strong [class.ok]="d.status==='ACTIVE'">{{d.status}}</strong><select [ngModel]="d.status" (ngModelChange)="changeStatus(d.deviceId,$event)"><option>ACTIVE</option><option>SUSPENDED</option><option>REVOKED</option><option>COMPROMISED</option></select></div>}</div>
  </section>
  <section class="panel"><div class="panel-title"><div><h2>Routes Backend → POServer</h2><p>Une route primaire par environnement. Aucun basculement aveugle après timeout.</p></div><button (click)="newRoute()">Ajouter</button></div>
    @for(r of routes();track r.environment){<div class="route"><input [(ngModel)]="r.environment" placeholder="Environnement"><select [(ngModel)]="r.primaryMode"><option value="REST_JSON">REST JSON</option><option value="ISO8583_PERSISTENT">ISO 8583 permanent</option></select><input [(ngModel)]="r.endpoint" placeholder="URL ou host:port"><label><input type="checkbox" [(ngModel)]="r.active"> Active</label><button (click)="saveRoute(r)">Enregistrer</button></div>}
  </section>
  <section class="panel"><h2>Dernières transactions</h2><div class="table"><div class="row tx head"><span>Référence</span><span>État</span><span>RC</span><span>Mise à jour</span></div>@for(t of transactions();track t.clientTransactionId){<div class="row tx"><code>{{t.clientTransactionId}}</code><strong [class.ok]="t.status==='APPROVED'">{{t.status}}</strong><span>{{t.responseCode||'—'}}</span><span>{{t.updatedAt|date:'medium'}}</span></div>}</div></section>
  @if(activation();as a){<section class="notice warning"><div><strong>Code d’activation à usage unique</strong><p>Transmettez-le par le canal sécurisé approuvé. Expiration : {{a.expiresAt|date:'medium'}}</p><code>{{a.activationCode}}</code></div><button (click)="activation.set(null)">Masquer</button></section>}
  `,
  styles:[`.page-header,.panel-title{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.eyebrow{color:var(--sg-color-primary);font-weight:700;text-transform:uppercase;font-size:11px;margin:0 0 5px}h1{margin:0;font-size:22px}h1 i{margin-right:8px;color:var(--sg-color-primary)}p{color:var(--sg-text-muted);margin:5px 0}button,select,input{border:1px solid var(--sg-border-strong);border-radius:var(--sg-radius);background:var(--sg-bg-surface);color:var(--sg-text-primary);padding:9px}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:18px 0}.summary article,.panel,.notice{background:var(--sg-bg-surface);border:1px solid var(--sg-border);border-radius:var(--sg-radius);padding:15px}.summary article{display:flex;flex-direction:column;gap:7px}.summary span,small{color:var(--sg-text-muted)}.summary strong{font-size:24px}.panel{margin-top:14px}.panel h2{font-size:16px;margin:0}.table{margin-top:12px}.row{display:grid;grid-template-columns:1fr 1.5fr .8fr .8fr 1fr;gap:10px;align-items:center;padding:9px;border-top:1px solid var(--sg-border)}.row span{display:flex;flex-direction:column}.row.head{font-size:11px;text-transform:uppercase;color:var(--sg-text-muted)}.row.tx{grid-template-columns:2fr 1fr .5fr 1.5fr}.ok{color:#16803c}.route{display:grid;grid-template-columns:1fr 1.2fr 2fr .7fr auto;gap:8px;margin-top:10px;align-items:center}.notice{margin-top:14px;display:flex;justify-content:space-between}.notice.error{border-color:#e19b94;color:#b42318}.notice.warning{border-color:#e7ba63}.notice code{display:block;margin-top:8px}@media(max-width:850px){.summary{grid-template-columns:1fr 1fr}.row,.route{grid-template-columns:1fr}.page-header,.panel-title{flex-direction:column}}`]
})
export class SoftPosWorkspaceComponent implements OnInit {
  private readonly api=inject(SoftPosAdminService); readonly devices=signal<any[]>([]); readonly routes=signal<SoftPosRoute[]>([]); readonly transactions=signal<any[]>([]); readonly activation=signal<any|null>(null); readonly busy=signal(false); readonly error=signal<string|null>(null);
  ngOnInit():void{this.load();} activeDevices():number{return this.devices().filter(d=>d.status==='ACTIVE').length;} activeRoutes():number{return this.routes().filter(r=>r.active).length;}
  load():void{this.busy.set(true);this.error.set(null);forkJoin({devices:this.api.devices(),routes:this.api.routes(),transactions:this.api.transactions()}).pipe(finalize(()=>this.busy.set(false))).subscribe({next:r=>{this.devices.set(r.devices);this.routes.set(r.routes);this.transactions.set(r.transactions);},error:()=>this.error.set('Le backend SoftPOS est indisponible ou non configuré.')});}
  issueActivation():void{const merchantId=prompt('Identifiant commerçant');const outletId=prompt('Identifiant PDV');const terminalId=prompt('TID SoftPOS (8 caractères)');if(!merchantId||!outletId||!terminalId)return;this.api.issueActivation(merchantId,outletId,terminalId).subscribe({next:a=>this.activation.set(a),error:()=>this.error.set('Activation impossible.')});}
  changeStatus(deviceId:string,status:SoftPosDeviceStatus):void{if((status==='REVOKED'||status==='COMPROMISED')&&!confirm(`Confirmer ${status} ?`))return;this.api.updateDevice(deviceId,status).subscribe({next:()=>this.load(),error:()=>this.error.set('Changement d’état refusé.')});}
  newRoute():void{this.routes.update(v=>[...v,{memberId:'',environment:'LAB',primaryMode:'REST_JSON',endpoint:'http://localhost:8530',connectTimeoutMillis:1500,responseTimeoutMillis:5000,active:false}]);}
  saveRoute(route:SoftPosRoute):void{this.api.saveRoute(route).subscribe({next:()=>this.load(),error:()=>this.error.set('La route n’a pas pu être enregistrée.')});}
}
