server:
  port: 8083
  servlet:
    context-path: /
spring:
  application:
    name: sg-dmcs-issuer
  datasource:
    url: jdbc:postgresql://localhost:5432/scenariogenerator
    username: scenario_user
    password: postgres123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: admin
      password: Admin123!
  liquibase:
    enabled: false
dmcs:
  base-dir: D:/MoneyCore/ScenarioGenerator/dmcs
  file-id-prefix: MC
mc:
  issuer:
    defaults:
      DE093_DEST_ID: "411111"
      DE094_ORIGIN_ID: "555555"
logging:
  level:
    com.staging.sg: INFO
  file:
    name: D:/MoneyCore/ScenarioGenerator/logs/dmcs-issuer.log
sg:
  persistence:
    module: DMCS_ISSUER
