gremlin.graph=org.janusgraph.core.JanusGraphFactory
storage.backend=berkeleyje
storage.directory=D:/LanaCash/OpenWay/installationOCI/fraud-tools-lite/data/janusgraph-berkeleyje
storage.berkeleyje.cache-percentage=10
schema.default=tp3
