<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.staging</groupId>
        <artifactId>scenario-generator</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>sg-generator-orchestrator</artifactId>
    <packaging>jar</packaging>
    <name>SG Generator Orchestrator</name>
    <description>Acquiring module — sends 0100, 0820, 0800</description>

    <dependencies>

        <!-- sg-common -->
        <dependency>
            <groupId>com.staging</groupId>
            <artifactId>sg-common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.staging</groupId>
            <artifactId>sg-deployment-core</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- Spring Boot Web -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <!-- WebSocket -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-websocket</artifactId>
        </dependency>

        <!-- Actuator -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>com.staging.sg.acquirer.SgAcquirerApplication</mainClass>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
