-- FuturPayment Fraud Monitoring - PostgreSQL schema v1
-- Apply with a migration role before starting sg-fraud-platform.
CREATE TABLE IF NOT EXISTS fraud_card_profile (id uuid PRIMARY KEY,member_id varchar(64) NOT NULL,token_hash varchar(64) NOT NULL,currency varchar(3) NOT NULL,country varchar(3) NOT NULL,customer_reference_hash varchar(64),status varchar(24) NOT NULL,created_at timestamptz NOT NULL,CONSTRAINT uk_fraud_card_member_token UNIQUE(member_id,token_hash));
CREATE TABLE IF NOT EXISTS fraud_monitoring_subject (id uuid PRIMARY KEY,member_id varchar(64) NOT NULL,sector_id varchar(64) NOT NULL,subject_type varchar(32) NOT NULL,subject_hash varchar(64) NOT NULL,status varchar(24) NOT NULL,created_at timestamptz NOT NULL,CONSTRAINT uk_fraud_subject_member_sector_type_hash UNIQUE(member_id,sector_id,subject_type,subject_hash));
CREATE TABLE IF NOT EXISTS fraud_risk_assessment (id uuid PRIMARY KEY,member_id varchar(64) NOT NULL,sector_id varchar(64) NOT NULL,transaction_reference varchar(128) NOT NULL,subject_type varchar(32) NOT NULL,subject_hash varchar(64) NOT NULL,score integer NOT NULL,band varchar(16) NOT NULL,recommended_action varchar(32) NOT NULL,enforced_action varchar(32) NOT NULL,model_version varchar(64) NOT NULL,reasons_json varchar(4000) NOT NULL,collective_group_size integer NOT NULL,collective_risk_score integer NOT NULL,created_at timestamptz NOT NULL,CONSTRAINT uk_fraud_assessment_member_tx UNIQUE(member_id,transaction_reference));
CREATE INDEX IF NOT EXISTS ix_fraud_assessment_member_created ON fraud_risk_assessment(member_id,created_at DESC);
CREATE INDEX IF NOT EXISTS ix_fraud_assessment_member_subject ON fraud_risk_assessment(member_id,subject_type,subject_hash,created_at DESC);
CREATE TABLE IF NOT EXISTS fraud_alert (id uuid PRIMARY KEY,member_id varchar(64) NOT NULL,assessment_id uuid NOT NULL UNIQUE,transaction_reference varchar(128) NOT NULL,score integer NOT NULL,band varchar(16) NOT NULL,status varchar(24) NOT NULL,created_at timestamptz NOT NULL);
CREATE INDEX IF NOT EXISTS ix_fraud_alert_member_created ON fraud_alert(member_id,created_at DESC);
CREATE TABLE IF NOT EXISTS fraud_feedback (id uuid PRIMARY KEY,member_id varchar(64) NOT NULL,alert_id uuid NOT NULL,outcome varchar(24) NOT NULL,comment varchar(500),created_at timestamptz NOT NULL);
CREATE INDEX IF NOT EXISTS ix_fraud_feedback_member_alert ON fraud_feedback(member_id,alert_id);
CREATE TABLE IF NOT EXISTS fraud_case (id uuid PRIMARY KEY,member_id varchar(64) NOT NULL,alert_id uuid NOT NULL,title varchar(160) NOT NULL,status varchar(24) NOT NULL,created_at timestamptz NOT NULL,CONSTRAINT uk_fraud_case_member_alert UNIQUE(member_id,alert_id));
CREATE TABLE IF NOT EXISTS fraud_decision_policy (id uuid PRIMARY KEY,member_id varchar(64) NOT NULL,mode varchar(24) NOT NULL,challenge_enabled boolean NOT NULL,hold_enabled boolean NOT NULL,block_enabled boolean NOT NULL,updated_at timestamptz NOT NULL,CONSTRAINT uk_fraud_policy_member UNIQUE(member_id));
CREATE TABLE IF NOT EXISTS fraud_entity_link (id uuid PRIMARY KEY,member_id varchar(64) NOT NULL,sector_id varchar(64) NOT NULL,subject_type varchar(32) NOT NULL,subject_hash varchar(64) NOT NULL,channel varchar(32) NOT NULL,entity_type varchar(32) NOT NULL,entity_hash varchar(64) NOT NULL,observation_count bigint NOT NULL,first_seen_at timestamptz NOT NULL,last_seen_at timestamptz NOT NULL,CONSTRAINT uk_fraud_link_member_sector_subject_entity UNIQUE(member_id,sector_id,subject_type,subject_hash,entity_type,entity_hash));
CREATE INDEX IF NOT EXISTS ix_fraud_link_member_entity ON fraud_entity_link(member_id,sector_id,entity_type,entity_hash,last_seen_at DESC);
CREATE INDEX IF NOT EXISTS ix_fraud_link_member_observations ON fraud_entity_link(member_id,observation_count DESC);
CREATE TABLE IF NOT EXISTS fraud_feature_snapshot (id uuid PRIMARY KEY,member_id varchar(64) NOT NULL,sector_id varchar(64) NOT NULL,transaction_reference varchar(128) NOT NULL,feature_version varchar(64) NOT NULL,features_json varchar(4000) NOT NULL,created_at timestamptz NOT NULL,CONSTRAINT uk_fraud_feature_member_tx UNIQUE(member_id,transaction_reference));
CREATE TABLE IF NOT EXISTS fraud_control_candidate (id uuid PRIMARY KEY,member_id varchar(64) NOT NULL,name varchar(120) NOT NULL,status varchar(24) NOT NULL,precision_value double precision NOT NULL,recall_value double precision NOT NULL,false_positive_rate double precision NOT NULL,governance_decision varchar(32) NOT NULL,created_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS fraud_threat_signal (id uuid PRIMARY KEY,member_id varchar(64) NOT NULL,indicator_type varchar(64) NOT NULL,indicator_hash varchar(64) NOT NULL,severity integer NOT NULL,source varchar(64) NOT NULL,expires_at timestamptz,created_at timestamptz NOT NULL,CONSTRAINT uk_fraud_signal_member_hash UNIQUE(member_id,indicator_type,indicator_hash));
CREATE TABLE IF NOT EXISTS fraud_event_outbox (id uuid PRIMARY KEY,member_id varchar(64) NOT NULL,sector_id varchar(64) NOT NULL,aggregate_type varchar(48) NOT NULL,aggregate_id varchar(128) NOT NULL,event_type varchar(64) NOT NULL,payload_json varchar(8000) NOT NULL,status varchar(24) NOT NULL,attempt_count integer NOT NULL,next_attempt_at timestamptz NOT NULL,created_at timestamptz NOT NULL,published_at timestamptz,CONSTRAINT uk_fraud_outbox_business_event UNIQUE(member_id,aggregate_type,aggregate_id,event_type));
CREATE INDEX IF NOT EXISTS ix_fraud_outbox_dispatch ON fraud_event_outbox(status,next_attempt_at,created_at);
CREATE TABLE IF NOT EXISTS fraud_event_route (id uuid PRIMARY KEY,member_id varchar(64) NOT NULL,sector_id varchar(64) NOT NULL,event_type varchar(64) NOT NULL,topic_template varchar(249) NOT NULL,schema_version varchar(32) NOT NULL,retention_class varchar(32) NOT NULL,enabled boolean NOT NULL,priority integer NOT NULL,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL,version bigint NOT NULL DEFAULT 0,CONSTRAINT uk_fraud_event_route_business_key UNIQUE(member_id,sector_id,event_type),CONSTRAINT ck_fraud_event_route_priority CHECK(priority BETWEEN 0 AND 1000));
CREATE INDEX IF NOT EXISTS ix_fraud_event_route_member_enabled ON fraud_event_route(member_id,enabled,sector_id,event_type);
CREATE TABLE IF NOT EXISTS fraud_graph_policy (id uuid PRIMARY KEY,member_id varchar(64) NOT NULL,sector_id varchar(64) NOT NULL,enabled boolean NOT NULL,cross_sector_enabled boolean NOT NULL,allowed_entity_types varchar(256) NOT NULL,minimum_group_size integer NOT NULL,base_score integer NOT NULL,score_per_additional_subject integer NOT NULL,maximum_score integer NOT NULL,observation_window_minutes integer NOT NULL,minimum_observations integer NOT NULL,maximum_hops integer NOT NULL,updated_at timestamptz NOT NULL,version bigint NOT NULL DEFAULT 0,CONSTRAINT uk_fraud_graph_policy_member_sector UNIQUE(member_id,sector_id));
CREATE TABLE IF NOT EXISTS fraud_ai_policy (id uuid PRIMARY KEY,member_id varchar(64) NOT NULL,sector_id varchar(64) NOT NULL,enabled boolean NOT NULL,governance_mode varchar(16) NOT NULL,champion_model varchar(96) NOT NULL,challenger_model varchar(96),challenger_traffic_percent integer NOT NULL,minimum_precision double precision NOT NULL,minimum_recall double precision NOT NULL,maximum_false_positive_rate double precision NOT NULL,drift_threshold double precision NOT NULL,drift_status varchar(16) NOT NULL,explainability_required boolean NOT NULL,analyst_approval_required boolean NOT NULL,alert_threshold integer NOT NULL,challenge_threshold integer NOT NULL,hold_threshold integer NOT NULL,block_threshold integer NOT NULL,updated_at timestamptz NOT NULL,version bigint NOT NULL DEFAULT 0,CONSTRAINT uk_fraud_ai_policy_member_sector UNIQUE(member_id,sector_id));
