import { DatePipe, DecimalPipe } from '@angular/common';
import { Component, inject, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { finalize, forkJoin } from 'rxjs';
import { SwitchLabCampaign, SwitchLabCampaignReport, SwitchLabCampaignRequest, SwitchLabCertificationManifest, SwitchLabEvidence, SwitchLabEvidenceRequest, SwitchLabProfileCapability, SwitchLabTestCatalogItem } from '../../core/models/product-contracts.models';
import { SwitchLabEnvironmentService } from '../../core/services/switchlab-environment.service';
import { SwitchLabTestCenterService } from '../../core/services/switchlab-test-center.service';

type Tab = 'catalog' | 'campaigns' | 'profiles' | 'reports' | 'evidence';

@Component({
  selector: 'app-switchlab-test-center', standalone: true, imports: [FormsModule, DatePipe, DecimalPipe],
  template: `
    <div class="page-header"><div><p class="eyebrow">SwitchLab · Lot 3</p><h1><i class="pi pi-chart-bar"></i> Campagnes & Tests</h1><p>Catalogue multi-simulateur, SLA, exécutions et preuves contrôlées.</p></div></div>
    <nav class="tabs">@for (item of tabs; track item.code) { <button type="button" [class.active]="tab() === item.code" (click)="tab.set(item.code)"><i [class]="item.icon"></i>{{ item.label }}</button> }</nav>
    @if (error()) { <div class="notice error"><i class="pi pi-exclamation-triangle"></i>{{ error() }}</div> }
    @if (loading()) { <div class="notice"><i class="pi pi-spin pi-spinner"></i> Chargement…</div> }

    @switch (tab()) {
      @case ('catalog') {
        <section class="filters"><label>Réseau<select [ngModel]="networkFilter()" (ngModelChange)="networkFilter.set($event)"><option value="">Tous</option>@for (network of networks(); track network) { <option [value]="network">{{ network }}</option> }</select></label></section>
        <div class="grid">@for (test of filteredCatalog(); track test.code) { <article class="card"><header><span class="badge">{{ test.network }}</span><span [class.available]="test.executable">{{ test.executable ? 'AUTOMATISABLE' : test.executionMode }}</span></header><h2>{{ test.label }}</h2><code>{{ test.code }}</code><p>{{ test.moduleCode }}</p>@if (test.requiredDataReferences.length) { <ul>@for (ref of test.requiredDataReferences; track ref) { <li><code>{{ ref }}</code></li> }</ul> }</article> }</div>
      }
      @case ('campaigns') {
        <form class="card form" (ngSubmit)="createCampaign()"><h2>Nouvelle campagne SwitchLab</h2><label>Nom<input name="name" [(ngModel)]="campaignForm.name" required /></label><label>Description<input name="description" [(ngModel)]="campaignForm.description" /></label><label>Profil<select name="profile" [(ngModel)]="campaignForm.profile">@for (profile of profiles(); track profile.code) { <option [value]="profile.code">{{ profile.label }}{{ profile.supported ? '' : ' — indisponible' }}</option> }</select></label><label>Disponibilité minimale (%)<input name="availability" type="number" min="0" max="100" [(ngModel)]="campaignForm.minimumAvailabilityPercent" /></label><label>Réponse p95 maximale (ms)<input name="response" type="number" min="1" [(ngModel)]="campaignForm.maximumResponseTimeMs" /></label><label>Durée (s)<input name="duration" type="number" min="1" max="30" [(ngModel)]="campaignForm.durationSeconds" /></label><label>TPS cible<input name="tps" type="number" min="1" max="50" [(ngModel)]="campaignForm.targetTps" /></label><label>Concurrence<input name="concurrency" type="number" min="1" max="16" [(ngModel)]="campaignForm.concurrency" /></label><label class="full">Références de données<textarea name="refs" [(ngModel)]="dataReferencesText" rows="3" placeholder="CARD_DATA=secret://provider/reference"></textarea></label><fieldset class="full"><legend>Tests</legend>@for (test of catalog(); track test.code) { <label class="check"><input type="checkbox" [checked]="campaignForm.testCodes.includes(test.code)" (change)="toggleTest(test.code, $any($event.target).checked)" />{{ test.label }} <small>{{ test.executionMode }}</small></label> }</fieldset><button class="primary" [disabled]="saving()">Enregistrer la campagne</button></form>
        <section class="list">@for (campaign of campaigns(); track campaign.id) { <article class="card"><header><div><h2>{{ campaign.name }}</h2><p>{{ campaign.description }}</p></div><span class="badge">{{ campaign.profile }}</span></header><p>{{ campaign.testCodes.length }} test(s) · SLA {{ campaign.minimumAvailabilityPercent }} % · {{ campaign.maximumResponseTimeMs }} ms</p><div class="actions"><button type="button" (click)="run(campaign)" [disabled]="saving() || !environment.selectedId() || !profileSupported(campaign.profile)"><i class="pi pi-play"></i> Exécuter</button></div></article> } @empty { <div class="notice">Aucune campagne SwitchLab.</div> }</section>
      }
      @case ('profiles') { <div class="grid">@for (profile of profiles(); track profile.code) { <article class="card"><header><h2>{{ profile.label }}</h2><span [class.available]="profile.supported">{{ profile.supported ? 'DISPONIBLE' : 'BLOQUÉ' }}</span></header><p>{{ profile.supported ? 'Exécution fonctionnelle multi-simulateur autorisée.' : profile.reason }}</p></article> }</div><div class="notice"><i class="pi pi-shield"></i>Les profils bloqués ne basculent jamais vers l’ancien moteur DMAS Member.</div> }
      @case ('reports') { <section class="list">@for (report of reports(); track report.executionId) { <article class="card report" [class.failed]="report.verdict === 'FAILED'"><header><div><h2>{{ report.verdict }}</h2><p>{{ report.startedAt | date:'medium' }} · {{ report.elapsedMillis }} ms</p></div><code>{{ report.correlationId }}</code></header><div class="metrics"><span>Disponibilité <strong>{{ report.actualAvailabilityPercent | number:'1.0-2' }} %</strong></span><span>Échantillons <strong>{{ report.sampleCount }}</strong></span><span>Erreurs <strong>{{ report.errorRatePercent | number:'1.0-2' }} %</strong></span><span>p95 <strong>{{ report.p95ResponseTimeMs }} ms</strong></span></div><div class="actions"><button type="button" (click)="download(report,'PDF')">PDF</button><button type="button" (click)="download(report,'XLSX')">XLSX</button></div><table><thead><tr><th>Test</th><th>Attendu</th><th>Obtenu</th><th>Verdict</th></tr></thead><tbody>@for (result of report.results; track result.testCode) { <tr><td>{{ result.testCode }}</td><td>{{ result.expected }}</td><td>{{ result.actual }}</td><td>{{ result.verdict }}</td></tr> }</tbody></table></article> } @empty { <div class="notice">Aucun rapport consolidé.</div> }</section> }
      @case ('evidence') { <form class="card form" (ngSubmit)="analyzeCertification()"><h2>Analyser un manifeste de certification</h2><div class="notice full">Le manifeste JSON doit référencer un artefact. PAN, PIN, clés et secrets sont refusés.</div><label class="full">Manifeste JSON<textarea name="manifest" [(ngModel)]="certificationManifestText" rows="8"></textarea></label><button class="primary" [disabled]="saving()">Analyser sans exécuter</button></form><form class="card form" (ngSubmit)="importEvidence()"><h2>Importer un résultat contrôlé</h2><div class="notice full">Seuls les compteurs et une référence d’artefact sont importés. Le navigateur ne lance aucune commande Maven, JUnit ou Playwright.</div><label>Source<select name="sourceType" [(ngModel)]="evidenceForm.sourceType"><option>JUNIT</option><option>PLAYWRIGHT</option><option>CERTIFICATION</option></select></label><label>Nom<input name="evidenceName" [(ngModel)]="evidenceForm.name" required /></label><label class="full">Référence contrôlée<input name="sourceReference" [(ngModel)]="evidenceForm.sourceReference" placeholder="artifact://ci/run/123/report" required /></label><label>Total<input name="total" type="number" min="0" [(ngModel)]="evidenceForm.total" /></label><label>Réussis<input name="passed" type="number" min="0" [(ngModel)]="evidenceForm.passed" /></label><label>Échoués<input name="failed" type="number" min="0" [(ngModel)]="evidenceForm.failed" /></label><button class="primary" [disabled]="saving()">Importer les métadonnées</button></form><section class="list">@for (item of evidence(); track item.id) { <article class="card"><header><div><h2>{{ item.name }}</h2><p>{{ item.sourceType }} · {{ item.importedAt | date:'medium' }}</p></div><span [class.available]="item.verdict === 'PASSED'">{{ item.verdict }}</span></header><p>{{ item.passed }}/{{ item.total }} réussis · {{ item.failed }} échoués</p><code>{{ item.sourceReference }}</code></article> }</section> }
    }
  `,
  styles: [`
    .page-header h1{display:flex;gap:10px;align-items:center;margin:0;font-size:21px}.page-header i{color:var(--sg-color-primary)}.page-header p,.card p{color:var(--sg-text-muted)}.eyebrow{margin:0 0 5px;text-transform:uppercase;letter-spacing:.08em;font-size:11px}.tabs{display:flex;flex-wrap:wrap;gap:7px;margin:18px 0}button{border:1px solid var(--sg-border-strong);border-radius:var(--sg-radius);padding:9px 13px;background:var(--sg-bg-surface);color:var(--sg-text-primary)}button.active,button.primary{color:#fff;background:var(--sg-color-primary);border-color:var(--sg-color-primary)}button i{margin-right:6px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:12px}.card,.notice{padding:17px;background:var(--sg-bg-surface);border:1px solid var(--sg-border);border-radius:var(--sg-radius);margin-top:12px}.card header{display:flex;justify-content:space-between;gap:12px}.card h2{margin:0 0 8px;font-size:16px}.badge{background:var(--sg-bg-muted);padding:4px 8px;border-radius:999px;font-size:11px}.available{color:#16803c}.error,.failed{color:#b42318}.notice i{margin-right:7px}.filters{margin-bottom:12px}.form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.form h2,.form .full{grid-column:1/-1}label{display:flex;flex-direction:column;gap:5px;color:var(--sg-text-muted);font-size:12px}input,select,textarea{border:1px solid var(--sg-border-strong);border-radius:var(--sg-radius);padding:9px;background:var(--sg-bg-surface);color:var(--sg-text-primary)}fieldset{border:1px solid var(--sg-border);border-radius:var(--sg-radius);display:grid;gap:7px}.check{display:grid;grid-template-columns:20px 1fr auto;align-items:center}.list{display:grid;gap:9px}.actions{display:flex;justify-content:flex-end}.metrics{display:flex;gap:20px;margin:12px 0}table{width:100%;border-collapse:collapse;font-size:12px}th,td{text-align:left;padding:8px;border-top:1px solid var(--sg-border)}code{overflow-wrap:anywhere;color:var(--sg-text-muted)}@media(max-width:800px){.form{grid-template-columns:1fr}.form h2,.form .full{grid-column:auto}.report{overflow:auto}}
  `],
})
export class SwitchLabTestCenterComponent implements OnInit {
  private readonly service=inject(SwitchLabTestCenterService); readonly environment=inject(SwitchLabEnvironmentService);
  readonly tab=signal<Tab>('catalog'); readonly loading=signal(false); readonly saving=signal(false); readonly error=signal<string|null>(null);
  readonly catalog=signal<SwitchLabTestCatalogItem[]>([]); readonly profiles=signal<SwitchLabProfileCapability[]>([]); readonly campaigns=signal<SwitchLabCampaign[]>([]); readonly reports=signal<SwitchLabCampaignReport[]>([]); readonly evidence=signal<SwitchLabEvidence[]>([]);
  readonly networkFilter=signal(''); readonly tabs=[{code:'catalog' as Tab,label:'Catalogue',icon:'pi pi-th-large'},{code:'campaigns' as Tab,label:'Campagnes',icon:'pi pi-list'},{code:'profiles' as Tab,label:'Charge & SLA',icon:'pi pi-chart-line'},{code:'reports' as Tab,label:'Rapports',icon:'pi pi-file'},{code:'evidence' as Tab,label:'Résultats externes',icon:'pi pi-upload'}];
  campaignForm:SwitchLabCampaignRequest={name:'',description:'',testCodes:[],profile:'FUNCTIONAL',minimumAvailabilityPercent:100,maximumResponseTimeMs:5000,durationSeconds:5,targetTps:5,concurrency:4,dataReferences:{}}; dataReferencesText='';
  evidenceForm:SwitchLabEvidenceRequest={sourceType:'JUNIT',name:'',sourceReference:'artifact://',total:0,passed:0,failed:0};
  certificationManifestText='{"name":"Network certification","network":"MASTERCARD","schemaVersion":"1.0","sourceReference":"artifact://certification/manifest","tests":[{"code":"MCD01"}]}';
  ngOnInit():void{this.loading.set(true);forkJoin({catalog:this.service.catalog(),profiles:this.service.profiles(),campaigns:this.service.campaigns(),reports:this.service.reports(),evidence:this.service.evidence(),environments:this.environment.load()}).pipe(finalize(()=>this.loading.set(false))).subscribe({next:data=>{this.catalog.set(data.catalog);this.profiles.set(data.profiles);this.campaigns.set(data.campaigns);this.reports.set(data.reports);this.evidence.set(data.evidence)},error:()=>this.error.set('Le Test Center SwitchLab n’est pas disponible.')})}
  networks():string[]{return [...new Set(this.catalog().map(item=>item.network))].sort()} filteredCatalog():SwitchLabTestCatalogItem[]{const network=this.networkFilter();return network?this.catalog().filter(item=>item.network===network):this.catalog()}
  toggleTest(code:string,checked:boolean):void{this.campaignForm.testCodes=checked?[...new Set([...this.campaignForm.testCodes,code])]:this.campaignForm.testCodes.filter(item=>item!==code)}
  createCampaign():void{try{this.campaignForm.dataReferences=this.parseRefs(this.dataReferencesText)}catch{this.error.set('Les références de données sont invalides.');return}this.saving.set(true);this.service.createCampaign(this.campaignForm).pipe(finalize(()=>this.saving.set(false))).subscribe({next:item=>{this.campaigns.update(items=>[item,...items]);this.campaignForm={name:'',description:'',testCodes:[],profile:'FUNCTIONAL',minimumAvailabilityPercent:100,maximumResponseTimeMs:5000,durationSeconds:5,targetTps:5,concurrency:4,dataReferences:{}};this.dataReferencesText=''},error:()=>this.error.set('La campagne n’a pas pu être enregistrée.')})}
  run(campaign:SwitchLabCampaign):void{const environmentId=this.environment.selectedId();if(!environmentId)return;this.saving.set(true);this.service.runCampaign(campaign.id,environmentId).pipe(finalize(()=>this.saving.set(false))).subscribe({next:report=>{this.reports.update(items=>[report,...items]);this.tab.set('reports')},error:()=>this.error.set('Exécution refusée ou indisponible. Vérifie le profil et les tests sélectionnés.')})}
  profileSupported(code:string):boolean{return this.profiles().find(item=>item.code===code)?.supported??false}
  download(report:SwitchLabCampaignReport,format:'PDF'|'XLSX'):void{this.service.exportReport(report.executionId,format).subscribe({next:blob=>{const href=URL.createObjectURL(blob);const link=document.createElement('a');link.href=href;link.download=`switchlab-report-${report.executionId}.${format.toLowerCase()}`;link.click();URL.revokeObjectURL(href)},error:()=>this.error.set('Export du rapport indisponible.')})}
  importEvidence():void{this.saving.set(true);this.service.importEvidence(this.evidenceForm).pipe(finalize(()=>this.saving.set(false))).subscribe({next:item=>{this.evidence.update(items=>[item,...items]);this.evidenceForm={sourceType:'JUNIT',name:'',sourceReference:'artifact://',total:0,passed:0,failed:0}},error:()=>this.error.set('Import refusé : utilise une référence contrôlée et des compteurs cohérents.')})}
  analyzeCertification():void{let manifest:SwitchLabCertificationManifest;try{manifest=JSON.parse(this.certificationManifestText) as SwitchLabCertificationManifest}catch{this.error.set('Le manifeste JSON est invalide.');return}this.saving.set(true);this.service.analyzeCertification(manifest).pipe(finalize(()=>this.saving.set(false))).subscribe({next:item=>this.evidence.update(items=>[item,...items]),error:()=>this.error.set('Analyse refusée : vérifie le schéma, la référence et l’absence de données sensibles.')})}
  private parseRefs(text:string):Record<string,string>{const refs:Record<string,string>={};for(const raw of text.split(/\r?\n/)){const line=raw.trim();if(!line)continue;const at=line.indexOf('=');if(at<1)throw new Error('invalid');refs[line.slice(0,at).trim()]=line.slice(at+1).trim()}return refs}
}
