package com.staging.sg.fraud.gateway.network;
import com.staging.sg.fraud.gateway.service.PermanentIsoKeyClientProcessor;import jakarta.annotation.*;import org.jpos.iso.*;import org.jpos.iso.channel.NACChannel;import org.jpos.iso.packager.ISO87APackager;import org.slf4j.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;import org.springframework.stereotype.Component;import java.time.*;import java.time.format.DateTimeFormatter;import java.util.concurrent.atomic.AtomicInteger;
@Component @ConditionalOnProperty(name="fraud-gateway.iso.client-enabled",havingValue="true")
public class PermanentIso8583Client{private static final Logger log=LoggerFactory.getLogger(PermanentIso8583Client.class);private final String host,signOn,echo,keyRequest;private final int port,echoSeconds,backoffSeconds;private final boolean requestTak;private final PermanentIsoKeyClientProcessor keys;private final AtomicInteger stan=new AtomicInteger();private volatile boolean running;private Thread thread;private NACChannel channel;
 public PermanentIso8583Client(@Value("${fraud-gateway.iso.remote-host}")String host,@Value("${fraud-gateway.iso.remote-port}")int port,@Value("${fraud-gateway.iso.echo-interval-seconds:30}")int echoSeconds,@Value("${fraud-gateway.iso.reconnect-backoff-seconds:5}")int backoffSeconds,@Value("${fraud-gateway.iso.request-tak-on-sign-on:true}")boolean requestTak,@Value("${fraud-gateway.iso.sign-on-code:001}")String signOn,@Value("${fraud-gateway.iso.echo-code:301}")String echo,@Value("${fraud-gateway.iso.key-request-code:101}")String keyRequest,PermanentIsoKeyClientProcessor keys){this.host=host;this.port=port;this.echoSeconds=echoSeconds;this.backoffSeconds=backoffSeconds;this.requestTak=requestTak;this.signOn=signOn;this.echo=echo;this.keyRequest=keyRequest;this.keys=keys;}
 @PostConstruct public void start(){running=true;thread=new Thread(this::loop,"fraud-iso-permanent-client");thread.setDaemon(true);thread.start();}
 @PreDestroy public void stop(){running=false;disconnect();if(thread!=null)thread.interrupt();}
 private void loop(){while(running){try{connect();exchange(network(signOn));if(requestTak)exchange(network(keyRequest));while(running&&channel.isConnected()){Thread.sleep(Duration.ofSeconds(echoSeconds).toMillis());exchange(network(echo));}}catch(Exception failure){if(running)log.warn("[FRAUD-ISO-CLIENT] link unavailable: {}",failure.getClass().getSimpleName());disconnect();sleepBackoff();}}}
 private void connect()throws Exception{channel=new NACChannel(host,port,new ISO87APackager(),null);channel.connect();log.info("[FRAUD-ISO-CLIENT] permanent link connected to {}:{}",host,port);}
 private ISOMsg exchange(ISOMsg request)throws Exception{channel.send(request);while(running){ISOMsg response=channel.receive();if(keys.isTakDelivery(response)){ISOMsg ack=keys.importAndAcknowledge(response);channel.send(ack);continue;}return response;}throw new IllegalStateException("Client stopped");}
 private ISOMsg network(String function)throws Exception{ISOMsg m=new ISOMsg();m.setPackager(new ISO87APackager());m.setMTI("0800");m.set(7,ZonedDateTime.now(ZoneOffset.UTC).format(DateTimeFormatter.ofPattern("MMddHHmmss")));m.set(11,String.format("%06d",stan.incrementAndGet()%1000000));m.set(70,function);return m;}
 private void disconnect(){try{if(channel!=null)channel.disconnect();}catch(Exception ignored){}}
 private void sleepBackoff(){try{Thread.sleep(Duration.ofSeconds(backoffSeconds).toMillis());}catch(InterruptedException interrupted){Thread.currentThread().interrupt();}}
}
