import { DatePipe } from '@angular/common';
import { Component, inject, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { finalize, forkJoin } from 'rxjs';
import { SwitchLabClearingArtifact, SwitchLabClearingEodResult, SwitchLabClearingNetwork } from '../../core/models/product-contracts.models';
import { SwitchLabClearingService } from '../../core/services/switchlab-clearing.service';

@Component({selector:'app-switchlab-clearing',standalone:true,imports:[FormsModule,DatePipe],template:`
<div class="page-header"><p class="eyebrow">SwitchLab · Lot 5</p><h1><i class="pi pi-file-import"></i> Réseaux Clearing</h1><p>Visa Base II, SWAM LIS et Mastercard DMCS dans un espace contrôlé.</p></div>
@if(error()){<div class="notice error">{{error()}}</div>}
<section class="grid">@for(network of networks();track network.code){<button type="button" class="card" [class.selected]="selected()?.code===network.code" (click)="selected.set(network)"><header><strong>{{network.label}}</strong><span>{{network.status}}</span></header><code>{{network.moduleCode}}</code><p>Upload {{network.uploadSupported?'oui':'non'}} · EOD {{network.eodSupported?'oui':'non'}} · Litiges {{network.disputesSupported?'oui':'non'}}</p>@for(limit of network.limitations;track limit){<small>{{limit}}</small>}</button>}</section>
@if(selected()){<section class="actions card"><h2>{{selected()!.label}}</h2><label>Date métier<input type="date" [(ngModel)]="businessDate" /></label><button type="button" [disabled]="!selected()!.eodSupported||busy()" (click)="runEod()">Lancer EOD</button><label class="upload">Fichier LIS<input type="file" accept=".lis,.dat,.txt" [disabled]="!selected()!.uploadSupported||busy()" (change)="upload($event)" /></label></section>}
@if(lastEod()){<div class="notice">EOD {{lastEod()!.networkCode}} : {{lastEod()!.status}} · <code>{{lastEod()!.evidenceReference}}</code></div>}
<section class="list"><h2>Artefacts contrôlés</h2>@for(item of artifacts();track item.id){<article class="card"><header><strong>{{item.fileName}}</strong><span>{{item.status}}</span></header><p>{{item.networkCode}} · {{item.recordCount}} record(s) · {{item.receivedAt|date:'medium'}}</p><code>{{item.evidenceReference}}</code></article>}@empty{<div class="notice">Aucun artefact importé.</div>}</section>
`,styles:[`.page-header h1{display:flex;gap:10px;align-items:center;margin:0}.page-header i{color:var(--sg-color-primary)}.page-header p,.card p,small{color:var(--sg-text-muted)}.eyebrow{text-transform:uppercase;font-size:11px;letter-spacing:.08em}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:12px}.card,.notice{padding:16px;margin-top:12px;border:1px solid var(--sg-border);border-radius:var(--sg-radius);background:var(--sg-bg-surface);color:var(--sg-text-primary);text-align:left}.card header{display:flex;justify-content:space-between;gap:12px}.card small{display:block;margin-top:6px}.selected{border-color:var(--sg-color-primary)}.actions{display:flex;align-items:end;flex-wrap:wrap;gap:12px}.actions h2{width:100%;margin:0}.actions label{display:flex;flex-direction:column;gap:5px}.actions button,.actions input{padding:9px;border:1px solid var(--sg-border-strong);border-radius:var(--sg-radius)}.error{color:#b42318}code{overflow-wrap:anywhere}`]})
export class SwitchLabClearingComponent implements OnInit{
 private readonly service=inject(SwitchLabClearingService);readonly networks=signal<SwitchLabClearingNetwork[]>([]);readonly artifacts=signal<SwitchLabClearingArtifact[]>([]);readonly selected=signal<SwitchLabClearingNetwork|null>(null);readonly lastEod=signal<SwitchLabClearingEodResult|null>(null);readonly busy=signal(false);readonly error=signal<string|null>(null);businessDate=new Date().toISOString().slice(0,10);
 ngOnInit():void{forkJoin({networks:this.service.networks(),artifacts:this.service.artifacts()}).subscribe({next:data=>{this.networks.set(data.networks);this.artifacts.set(data.artifacts);if(data.networks.length)this.selected.set(data.networks[0])},error:()=>this.error.set('Le cockpit Clearing est indisponible.')})}
 runEod():void{const network=this.selected();if(!network)return;this.busy.set(true);this.service.eod({networkCode:network.code,businessDate:this.businessDate}).pipe(finalize(()=>this.busy.set(false))).subscribe({next:value=>this.lastEod.set(value),error:()=>this.error.set('Le traitement EOD a échoué ou l’adaptateur n’est pas configuré.')})}
 upload(event:Event):void{const file=(event.target as HTMLInputElement).files?.[0];const network=this.selected();if(!file||!network)return;this.busy.set(true);this.service.upload(network.code,file).pipe(finalize(()=>this.busy.set(false))).subscribe({next:item=>this.artifacts.update(items=>[item,...items]),error:()=>this.error.set('Import refusé : vérifie le format, la taille et l’adaptateur Clearing.')})}
}
